### ISSUE TITLE
Querying with n to limit max results returns 400

### ISSUE THREAD

**Issue by KaustubhDeshmukh** [centrifugal-rama/log_collection#9]
Querying with n to limit max results returns 400
<img width="595" alt="Screenshot 2024-02-14 at 10 44 41 AM" src="https://github.com/centrifugal-rama/log_collection/assets/3673773/5b84852d-1f94-4b10-b80e-ed9c3f7f0697">

**Comment by centrifugal-rama** [comment]
Merged. Closing.
